### ISSUE TITLE
Consider using dry-python/returns

### ISSUE THREAD

**Issue by sobolevn** [christianscott/express-your-self#1]
Thanks a lot for this project! It was a lot of fun reading through the source code.

I can suggest to add [`returns`](https://github.com/dry-python/returns). It is a collection of typed monads and tools to work with them. It might be helpful to:
1. Get rid of `None` and `if some is None:` checks with the help of `Maybe`
2. Remove exception and turn them into `Result` objects

This statement-less style might heavily benefit from it!

**Comment by christianscott** [comment]
Thanks for taking a look! Looks like a really cool library, I'm a huge fan of the `Maybe` monad. I'd like to keep it simple & just use the standard library for this project, but I appreciate the suggestion 🙂
